// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: proto/example.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExampleServiceClient interface {
	// Example unary rpc
	ExampleUnary(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error)
	// Example bidi streaming rpc
	ExampleStreaming(ctx context.Context, opts ...grpc.CallOption) (ExampleService_ExampleStreamingClient, error)
}

type exampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleServiceClient(cc grpc.ClientConnInterface) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) ExampleUnary(ctx context.Context, in *ExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error) {
	out := new(ExampleResponse)
	err := c.cc.Invoke(ctx, "/example.ExampleService/ExampleUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleServiceClient) ExampleStreaming(ctx context.Context, opts ...grpc.CallOption) (ExampleService_ExampleStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &ExampleService_ServiceDesc.Streams[0], "/example.ExampleService/ExampleStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &exampleServiceExampleStreamingClient{stream}
	return x, nil
}

type ExampleService_ExampleStreamingClient interface {
	Send(*ExampleRequest) error
	Recv() (*ExampleResponse, error)
	grpc.ClientStream
}

type exampleServiceExampleStreamingClient struct {
	grpc.ClientStream
}

func (x *exampleServiceExampleStreamingClient) Send(m *ExampleRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exampleServiceExampleStreamingClient) Recv() (*ExampleResponse, error) {
	m := new(ExampleResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExampleServiceServer is the server API for ExampleService service.
// All implementations must embed UnimplementedExampleServiceServer
// for forward compatibility
type ExampleServiceServer interface {
	// Example unary rpc
	ExampleUnary(context.Context, *ExampleRequest) (*ExampleResponse, error)
	// Example bidi streaming rpc
	ExampleStreaming(ExampleService_ExampleStreamingServer) error
	mustEmbedUnimplementedExampleServiceServer()
}

// UnimplementedExampleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedExampleServiceServer struct {
}

func (UnimplementedExampleServiceServer) ExampleUnary(context.Context, *ExampleRequest) (*ExampleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExampleUnary not implemented")
}
func (UnimplementedExampleServiceServer) ExampleStreaming(ExampleService_ExampleStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method ExampleStreaming not implemented")
}
func (UnimplementedExampleServiceServer) mustEmbedUnimplementedExampleServiceServer() {}

// UnsafeExampleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleServiceServer will
// result in compilation errors.
type UnsafeExampleServiceServer interface {
	mustEmbedUnimplementedExampleServiceServer()
}

func RegisterExampleServiceServer(s grpc.ServiceRegistrar, srv ExampleServiceServer) {
	s.RegisterService(&ExampleService_ServiceDesc, srv)
}

func _ExampleService_ExampleUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).ExampleUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.ExampleService/ExampleUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).ExampleUnary(ctx, req.(*ExampleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleService_ExampleStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExampleServiceServer).ExampleStreaming(&exampleServiceExampleStreamingServer{stream})
}

type ExampleService_ExampleStreamingServer interface {
	Send(*ExampleResponse) error
	Recv() (*ExampleRequest, error)
	grpc.ServerStream
}

type exampleServiceExampleStreamingServer struct {
	grpc.ServerStream
}

func (x *exampleServiceExampleStreamingServer) Send(m *ExampleResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exampleServiceExampleStreamingServer) Recv() (*ExampleRequest, error) {
	m := new(ExampleRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExampleService_ServiceDesc is the grpc.ServiceDesc for ExampleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExampleUnary",
			Handler:    _ExampleService_ExampleUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExampleStreaming",
			Handler:       _ExampleService_ExampleStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/example.proto",
}
